# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 209507ebd27ce05057f8b01706cff9c7965195806ccc2927b57c370d32ad3e6b5138cdd95c62d4349822196a764717109a6a065ba855bef3ef927ed6f8720312

test:
  secret_key_base: ce012fe903d4d16ea0a98ce00f6cc610710feddc2931b935048b8d7c105a3c394f212844846808b9cc476ea42eb7108ddbe011ba32fa863291843f9b1e4d4a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
